name: Test package

on: push

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel scmver setuptools

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Install package
      run: pip install dist/qiskit_scaleway-${version}-py3-none-any.whl

    - name: Install test
      run: pip install -r tests/requirements.txt

    - name: Run test
      run: pytest -s --showprogress -vv tests/
      env:
        QISKIT_SCALEWAY_PROJECT_ID: ${{ secrets.STG_QISKIT_SCALEWAY_PROJECT_ID }}
        QISKIT_SCALEWAY_API_TOKEN: ${{ secrets.STG_QISKIT_SCALEWAY_API_TOKEN }}
        QISKIT_SCALEWAY_API_URL: ${{ secrets.STG_QISKIT_SCALEWAY_API_URL }}